### ISSUE TITLE
Noticed a problem

### ISSUE THREAD

**Issue by MurilloSeb** [JamesTaylor-creator/Tic-Tac-Toe-COSC-1436-301#2]
I was trying to run this program on my Python but it won't let me run until I intended a certain spot before the "board = [' ' for x in range(10)]" statement,  posting this if anybody else is having trouble running the file.

Example:

def main():

    board = [' ' for x in range(10)]

def insertLetter(letter, pos):
    board[pos] = letter

def spaceIsFree(pos):
    return board[pos] == ' '

**Comment by JamesTaylor-creator** [comment]
Sorry about the late reply, the program is running fine, I just checked, If
you created a new branch, just merge and pull. If your having trouble with
visual studio, run as administrator. We will be tearing the project apart
and creating classes to prep for creating a graphical interface as a
stretch goal.

**Comment by JamesTaylor-creator** [comment]
There are also a few bugs we need to fix to complete the requirements
listed in our project.
